# clean up directories before doing anything is a good thing.. aah the fresh smell of clean :)
---
# fixme: this should have checks as it can mean dataloss and downtime
- name: Prune everything in docker
  community.docker.docker_prune:
    containers: true
    images: true
    images_filters:
      dangling: false
    networks: true
    volumes: true
    builder_cache: true
  when: migrid_clean_docker_prune_all == true

- name: Remove {{ migrid_overlay }}
  file:
    path: "{{ migrid_overlay }}"
    state: absent
  when: migrid_clean_remove_overlay == true

- name: Remove {{ migrid_root }}
  git:
    dest: "{{ migrid_root }}"
    repo: "{{ migrid_docker_repository }}"
    force: true
    update: true
    clone: false
  when:
    - migrid_clean_git_reset == true
    - migrid_clean_remove_app_root == false
    - migrid_docker_repository is defined

- name: Remove {{ migrid_root }}
  file:
    path: "{{ migrid_root }}"
    state: absent
  when:
    - migrid_clean_remove_app_root == true
