---
# copies overlay files onto server. They are placed in a directory besides migrid
- name: Create directory for migrid-overlay
  file:
    path: "{{ migrid_overlay }}"
    owner: "{{ migrid_adm }}"
    group: "{{ migrid_adm }}"
    state: directory
    mode: "0755"

- name: copy overlay files to server
  synchronize:
    src: "{{ migrid_copy_overlay_files_src }}"
    dest: "{{ migrid_copy_overlay_files_dest }}"

- name: Changer owner on all files
  file:
    path: "{{ migrid_overlay }}"
    owner: "{{ migrid_adm }}"
    group: "{{ migrid_adm }}"
    recurse: true
