#this will do that baseline stuff needed for doing migrid on the server
# depends on migrid-users
---
- name: Create directory for MiGrid
  ansible.builtin.file:
    path: "{{ migrid_root }}"
    owner: "{{ migrid_adm }}"
    group: "{{ migrid_adm }}"
    state: directory

- name: Set safe.directory for {{ migrid_root }}
  ansible.builtin.command:
    cmd: git config --global --add safe.directory {{ migrid_root }}
    chdir: "{{ migrid_root }}"

- name: Clone docker-migrid
  become_user: "{{ migrid_adm }}"
  become: true
  ansible.builtin.git:
    repo: "{{ migrid_docker_repository }}"
    dest: "{{ migrid_root }}"
    version: "{{ migrid_docker_repository_version | default('master') }}"

- name: Link .env in migrid_root
  ansible.builtin.file:
    src: "{{ migrid_baseline_env_src }}"
    dest: "{{ migrid_root }}/.env"
    state: link
    force: false

- name: Set Dockerfile
  ansible.builtin.file:
    src: Dockerfile.{{ migrid_container_type }}
    dest: "{{ migrid_root }}/Dockerfile"
    state: link

- name: Set docker-compose.override.yml
  ansible.builtin.template:
    src: docker-compose.override.yml.j2
    dest: "{{ migrid_root }}/docker-compose.override.yml"
    owner: "{{ migrid_adm }}"
    group: "{{ migrid_adm }}"
  when: migrid_docker_compose_override is defined

- name: Link to existing docker-compose.yml
  ansible.builtin.file:
    src: "{{ migrid_root }}/{{ migrid_docker_compose_preset }}"
    dest: "{{ migrid_root }}/docker-compose.yml"
    state: link
  when:
    - migrid_docker_compose_preset is defined
    - migrid_docker_compose_custom is undefined

- name: Copy custom docker-compose.yml
  ansible.builtin.copy:
    src: "{{ migrid_docker_compose_custom }}"
    dest: "{{ migrid_root }}/"
    owner: "{{ migrid_adm }}"
    group: "{{ migrid_adm }}"
  when: migrid_docker_compose_custom is defined

- name: Link to custom docker-compose.yml
  ansible.builtin.file:
    src: "{{ migrid_root }}/{{ migrid_docker_compose_custom | basename }}"
    dest: "{{ migrid_root }}/docker-compose.yml"
    state: link
    force: true
  when: migrid_docker_compose_custom is defined
